[package]
name = "tmw-japanese-core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lindera = { version = "=5.3.0", features = ["embed-ipadic"], optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
unicode-normalization = "0.1.24"

[features]
default = ["tokenizer"]
tokenizer = ["dep:lindera"]

[dev-dependencies]
tempfile = "3.14.0"
