import { useCallback, useEffect, useRef, useState } from "react";
import { convertFileSrc, invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { BookDetailsPanel } from "./BookDetailsPanel";

const navigation = [
  ["all", "すべての本", "All Books"], ["roots", "ライブラリルート", "Library Roots"],
  ["recent", "最近追加", "Recently Added"], ["attention", "要確認のメタデータ", "Metadata Needs Attention"],
  ["tags", "タグ", "Tags"], ["collections", "コレクション", "Collections"], ["settings", "設定", "Settings"],
] as const;
const words = {
  library: ["ライブラリ", "Library"], grid: ["グリッド", "Grid"], list: ["リスト", "List"],
  unknownAuthor: ["著者不明", "Unknown author"], sort: ["並べ替え", "Sort"], rootFilter: ["ライブラリルートで絞り込み", "Filter by library root"], tagFilter: ["タグで絞り込み", "Filter by tag"], collectionFilter: ["コレクションで絞り込み", "Filter by collection"],
  allRoots: ["すべてのルート", "All roots"], allTags: ["すべてのタグ", "All tags"], allCollections: ["すべてのコレクション", "All collections"], attentionOnly: ["要確認のみ", "Needs attention only"],
  titleSort: ["タイトル順", "Title"], authorSort: ["著者順", "Author"], seriesSort: ["シリーズ順", "Series"], addedSort: ["追加日順", "Date added"], modifiedSort: ["更新日順", "File modified"], folderSort: ["フォルダー順", "Folder"],
  search: ["タイトル・著者・フォルダーを検索", "Search title, author, folder…"],
  noMatches: ["条件に一致する本はありません。", "No books match these filters."], addFolderPrompt: ["フォルダーを追加して EPUB ライブラリを読み込みましょう。", "Add a folder to start cataloging your EPUB library."],
  addFolder: ["フォルダーを追加", "Add folder"], readOnly: ["選んだフォルダーは読み取り専用でスキャンします。", "Selected folders are scanned read-only."], scanning: ["スキャン中", "Scanning"], cancel: ["キャンセル", "Cancel"], rescan: ["再スキャン", "Rescan"], removeCatalog: ["カタログから削除", "Remove from catalog"], noRoots: ["まだライブラリルートがありません。", "No library roots yet."],
  coverCache: ["カバーキャッシュ", "Cover cache"], cacheNote: ["EPUB は変更しません。抽出したカバーだけを、ライブラリとは別のフォルダーへ保存します。", "EPUB files are never changed. Extracted covers are saved separately from your library."], currentLocation: ["現在の場所", "Current location"], loading: ["読み込み中…", "Loading…"], changeLocation: ["保存先を変更", "Change location"], regenerateCovers: ["カバーキャッシュを再生成", "Regenerate cover cache"], cacheSafe: ["このキャッシュは再生成できます。削除してもカタログや元の EPUB は失われません。", "This cache can be regenerated. Deleting it never removes catalog data or source EPUBs."], language: ["言語", "Language"], booksShown: ["冊を表示", "books shown"],
} as const;
const PAGE_SIZE = 80;
type Root = { id: number; path: string; displayName: string; lastScannedAt: number | null; bookCount: number };
type Book = { id: number; fileName: string; parentFolderPath: string; effectiveTitle: string; effectiveCreator: string; effectiveSeries: string; effectiveVolume: string; effectiveCoverPath: string | null };
type Choice = [number, string]; type Sort = "title" | "author" | "series" | "dateAdded" | "modified" | "folder";
type Progress = { scanId: string; discoveredCount: number; changedCount: number; currentPath: string };
const time = (value: number | null, language: "ja" | "en") => value ? new Intl.DateTimeFormat(language === "ja" ? "ja-JP" : "en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value * 1000)) : language === "ja" ? "未スキャン" : "Not scanned";

function Cover({ book, language }: { book: Book; language: "ja" | "en" }) {
  const [broken, setBroken] = useState(false);
  if (book.effectiveCoverPath && !broken) return <img className="h-full w-full object-cover" src={convertFileSrc(book.effectiveCoverPath)} alt="" onError={() => setBroken(true)} />;
  return <div className="grid h-full w-full place-items-center bg-gradient-to-br from-amber-300/30 to-stone-800 text-3xl text-amber-100/70">{language === "ja" ? "本" : "Book"}</div>;
}

export function LibraryShell() {
  const [roots, setRoots] = useState<Root[]>([]), [books, setBooks] = useState<Book[]>([]), [tags, setTags] = useState<Choice[]>([]), [collections, setCollections] = useState<Choice[]>([]);
  const [language, setLanguage] = useState<"ja" | "en">(() => localStorage.getItem("tmw-interface-language") === "en" ? "en" : "ja");
  const [active, setActive] = useState("all"), [layout, setLayout] = useState<"grid" | "list">("grid"), [sort, setSort] = useState<Sort>("title"), [rootId, setRootId] = useState<number>(), [tagId, setTagId] = useState<number>(), [collectionId, setCollectionId] = useState<number>(), [needsMetadata, setNeedsMetadata] = useState(false), [searchInput, setSearchInput] = useState(""), [query, setQuery] = useState("");
  const [progress, setProgress] = useState<Progress | null>(null), [error, setError] = useState<string | null>(null), [cache, setCache] = useState<string | null>(null), [hasMore, setHasMore] = useState(false);
  const [detailBookId, setDetailBookId] = useState<number | null>(null), [selectedBookIds, setSelectedBookIds] = useState<number[]>([]), [batchTags, setBatchTags] = useState("");
  const sentinel = useRef<HTMLDivElement>(null);
  const t = (key: keyof typeof words) => words[key][language === "ja" ? 0 : 1];
  const switchLanguage = () => setLanguage(current => { const next = current === "ja" ? "en" : "ja"; localStorage.setItem("tmw-interface-language", next); return next; });
  const refreshRoots = useCallback(async () => setRoots(await invoke<Root[]>("list_library_roots")), []);
  const load = useCallback(async (offset = 0) => {
    const rows = await invoke<Book[]>("browse_books", { request: { libraryRootId: rootId, tagId, collectionId, needsMetadata, query, sort, offset, limit: PAGE_SIZE } });
    setBooks(old => offset ? [...old, ...rows] : rows); setHasMore(rows.length === PAGE_SIZE);
  }, [collectionId, needsMetadata, query, rootId, sort, tagId]);
  // These asynchronous catalog reads are the initial synchronization with the Tauri backend.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void refreshRoots().catch(reason => setError(String(reason))); void invoke<Choice[]>("list_tags").then(setTags).catch(reason => setError(String(reason))); void invoke<Choice[]>("list_collections").then(setCollections).catch(reason => setError(String(reason))); void invoke<string>("get_cover_cache_directory").then(setCache).catch(reason => setError(String(reason))); }, [refreshRoots]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load().catch(reason => setError(String(reason))); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => setQuery(searchInput), 180); return () => window.clearTimeout(timer); }, [searchInput]);
  useEffect(() => { const observer = new IntersectionObserver(entries => { if (entries[0]?.isIntersecting && hasMore) void load(books.length).catch(reason => setError(String(reason))); }, { rootMargin: "600px" }); if (sentinel.current) observer.observe(sentinel.current); return () => observer.disconnect(); }, [books.length, hasMore, load]);
  useEffect(() => { const pending = Promise.all([listen<Progress>("scan-progress", ({ payload }) => setProgress(payload)), listen("scan-completed", () => { setProgress(null); void refreshRoots(); void load(); }), listen<{ message: string }>("scan-failed", ({ payload }) => setError(payload.message))]); return () => { void pending.then(all => all.forEach(stop => stop())); }; }, [load, refreshRoots]);
  const add = async () => { const path = await invoke<string | null>("choose_library_folder"); if (!path) return; try { await invoke("add_library_root", { path }); await refreshRoots(); setActive("roots"); } catch (reason) { setError(String(reason)); } };
  const rescan = async (root: Root) => { const scanId = crypto.randomUUID(); setProgress({ scanId, discoveredCount: 0, changedCount: 0, currentPath: root.path }); try { await invoke("rescan_library_root", { rootId: root.id, scanId }); } catch (reason) { setError(String(reason)); setProgress(null); } };
  const remove = async (root: Root) => { if (!window.confirm(language === "ja" ? `「${root.displayName}」をカタログから削除します。EPUB ファイルは変更されません。` : `Remove “${root.displayName}” from the catalog? EPUB files will not be changed.`)) return; await invoke("remove_library_root", { rootId: root.id }); await refreshRoots(); void load(); };
  const select = (item: string) => { setActive(item); setNeedsMetadata(item === "attention"); if (item === "recent") setSort("dateAdded"); };
  const filters = <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><input type="search" className="control xl:col-span-2" value={searchInput} onChange={e => setSearchInput(e.target.value)} placeholder={t("search")} aria-label={t("search")} /><select aria-label={t("sort")} className="control" value={sort} onChange={e => setSort(e.target.value as Sort)}><option value="title">{t("titleSort")}</option><option value="author">{t("authorSort")}</option><option value="series">{t("seriesSort")}</option><option value="dateAdded">{t("addedSort")}</option><option value="modified">{t("modifiedSort")}</option><option value="folder">{t("folderSort")}</option></select><select aria-label={t("rootFilter")} className="control" value={rootId ?? ""} onChange={e => setRootId(e.target.value ? Number(e.target.value) : undefined)}><option value="">{t("allRoots")}</option>{roots.map(r => <option key={r.id} value={r.id}>{r.displayName}</option>)}</select><select aria-label={t("tagFilter")} className="control" value={tagId ?? ""} onChange={e => setTagId(e.target.value ? Number(e.target.value) : undefined)}><option value="">{t("allTags")}</option>{tags.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label={t("collectionFilter")} className="control" value={collectionId ?? ""} onChange={e => setCollectionId(e.target.value ? Number(e.target.value) : undefined)}><option value="">{t("allCollections")}</option>{collections.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><label className="flex items-center gap-2 rounded-lg border border-white/10 bg-stone-900 px-3 text-sm"><input type="checkbox" checked={needsMetadata} onChange={e => setNeedsMetadata(e.target.checked)} />{t("attentionOnly")}</label></div>;
  const browser = <section className="w-full self-start">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-amber-300">{t("library")}</p><h1 className="mt-1 text-3xl font-semibold">{navigation.find(([id]) => id === (needsMetadata ? "attention" : "all"))?.[language === "ja" ? 1 : 2]}</h1><p className="mt-1 text-sm text-stone-400">{books.length}{hasMore ? "+" : ""} {t("booksShown")}</p></div><div className="flex rounded-lg border border-white/10 p-1"><button aria-pressed={layout === "grid"} className="rounded px-3 py-2 text-sm" onClick={() => setLayout("grid")}>{t("grid")}</button><button aria-pressed={layout === "list"} className="rounded px-3 py-2 text-sm" onClick={() => setLayout("list")}>{t("list")}</button></div></div>
    {filters}
    {selectedBookIds.length > 0 && <div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border border-amber-300/30 bg-amber-300/10 p-3 text-sm"><span>{selectedBookIds.length} selected</span><input className="control max-w-xs" value={batchTags} onChange={e => setBatchTags(e.target.value)} placeholder="Replace tags, comma separated" /><button className="rounded bg-amber-300 px-3 py-2 font-medium text-stone-950" onClick={() => void invoke("batch_set_book_tags", { request: { bookIds: selectedBookIds, tagNames: batchTags.split(",") } }).then(() => { setSelectedBookIds([]); setBatchTags(""); void load(); }).catch(reason => setError(String(reason)))}>Apply tags</button><button className="text-stone-300 underline" onClick={() => setSelectedBookIds([])}>Clear</button></div>}
    {books.length === 0 ? <div className="rounded-xl border border-dashed border-white/15 p-12 text-center text-stone-400">{roots.length ? t("noMatches") : t("addFolderPrompt")}</div> : <div className={layout === "grid" ? "grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-6" : "overflow-hidden rounded-xl border border-white/10"}>
      {books.map(book => { const checked = selectedBookIds.includes(book.id); const toggle = () => setSelectedBookIds(current => checked ? current.filter(id => id !== book.id) : [...current, book.id]); return layout === "grid" ? <article key={book.id} className="relative min-w-0"><label className="absolute left-2 top-2 z-10 rounded bg-stone-950/80 p-1"><input aria-label={`Select ${book.effectiveTitle}`} type="checkbox" checked={checked} onChange={toggle} /></label><button className="block w-full text-left" onClick={() => setDetailBookId(book.id)}><div className="aspect-[2/3] overflow-hidden rounded-xl bg-stone-900 shadow-lg"><Cover book={book} language={language} /></div><h2 className="mt-3 truncate font-medium" title={book.effectiveTitle}>{book.effectiveTitle}</h2><p className="mt-1 truncate text-sm text-stone-400">{book.effectiveCreator || t("unknownAuthor")}</p><p className="truncate text-xs text-amber-200/80">{[book.effectiveSeries, book.effectiveVolume].filter(Boolean).join(" · ")}</p></button></article> : <article key={book.id} className="flex gap-4 border-b border-white/10 p-3 last:border-0"><label className="pt-1"><input aria-label={`Select ${book.effectiveTitle}`} type="checkbox" checked={checked} onChange={toggle} /></label><button className="flex min-w-0 flex-1 gap-4 text-left" onClick={() => setDetailBookId(book.id)}><div className="h-20 w-14 shrink-0 overflow-hidden rounded bg-stone-800"><Cover book={book} language={language} /></div><div className="min-w-0"><h2 className="truncate font-medium">{book.effectiveTitle}</h2><p className="mt-1 truncate text-sm text-stone-400">{book.effectiveCreator || t("unknownAuthor")}</p><p className="mt-1 truncate text-xs text-amber-200/80">{[book.effectiveSeries, book.effectiveVolume].filter(Boolean).join(" · ") || book.parentFolderPath}</p></div></button></article>; })}
    </div>}
    <div ref={sentinel} className="h-px" />
  </section>;
  const rootsView = <section className="w-full max-w-4xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-amber-300">{language === "ja" ? "設定" : "Settings"}</p><h1 className="mt-1 text-3xl font-semibold">{language === "ja" ? "ライブラリルート" : "Library Roots"}</h1><p className="mt-2 text-stone-400">{language === "ja" ? "選んだフォルダーは読み取り専用でスキャンします。" : "Selected folders are scanned read-only."}</p></div><button className="primary" onClick={() => void add()}>{t("addFolder")}</button></div>{progress && <div className="mb-4 rounded-lg bg-stone-900 p-4 text-sm text-stone-300"><p>{language === "ja" ? `スキャン中: ${progress.discoveredCount} 件を検出、${progress.changedCount} 件を更新` : `Scanning: ${progress.discoveredCount} found, ${progress.changedCount} updated`}</p><p className="mt-1 truncate text-xs text-stone-500">{progress.currentPath}</p><button className="mt-3 text-amber-300 underline" onClick={() => void invoke("cancel_scan", { scanId: progress.scanId })}>{t("cancel")}</button></div>}<div className="overflow-hidden rounded-xl border border-white/10 bg-stone-900/60">{roots.length === 0 ? <p className="p-8 text-center text-stone-400">{t("noRoots")}</p> : roots.map(root => <div key={root.id} className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 p-5 last:border-0"><div className="min-w-0"><p className="font-medium">{root.displayName}</p><p className="mt-1 truncate text-sm text-stone-400">{root.path}</p><p className="mt-2 text-xs text-stone-500">{root.bookCount} {language === "ja" ? "冊 · 最終スキャン:" : "books · Last scanned:"} {time(root.lastScannedAt, language)}</p></div><div className="flex gap-3"><button className="text-sm text-amber-300" onClick={() => void rescan(root)}>{t("rescan")}</button><button className="text-sm text-stone-400 hover:text-red-300" onClick={() => void remove(root)}>{t("removeCatalog")}</button></div></div>)}</div></section>;
  const settings = <section className="w-full max-w-4xl"><p className="text-sm font-medium text-amber-300">{language === "ja" ? "設定" : "Settings"}</p><h1 className="mt-1 text-3xl font-semibold">{t("coverCache")}</h1><p className="mt-2 text-stone-400">{t("cacheNote")}</p><div className="mt-6 rounded-xl border border-white/10 bg-stone-900/60 p-5"><p className="text-sm text-stone-400">{t("currentLocation")}</p><p className="mt-2 break-all font-medium">{cache ?? t("loading")}</p><div className="mt-5 flex flex-wrap gap-3"><button className="primary" onClick={async () => { const path = await invoke<string | null>("choose_cover_cache_folder"); if (path) { await invoke("set_cover_cache_directory", { path }); setCache(path); } }}>{t("changeLocation")}</button><button className="rounded-xl border border-amber-300/50 px-5 py-3 font-semibold text-amber-200" onClick={() => void invoke("regenerate_cover_cache").catch(reason => setError(String(reason)))}>{t("regenerateCovers")}</button></div><p className="mt-4 text-xs leading-5 text-stone-500">{t("cacheSafe")}</p></div></section>;
  return <div className="min-h-screen bg-stone-950 text-stone-100"><div className="mx-auto flex min-h-screen max-w-[1800px] flex-col md:flex-row"><aside className="border-b border-white/10 bg-stone-900/70 px-5 py-6 md:w-72 md:border-b-0 md:border-r"><div className="mb-8 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-amber-400 text-lg font-black text-stone-950">本</div><div><p className="font-semibold">TMW Library</p><p className="text-xs text-stone-400">{language === "ja" ? "ローカル EPUB ライブラリ" : "Local EPUB library"}</p></div></div><nav aria-label="Main navigation" className="grid gap-1 sm:grid-cols-2 md:grid-cols-1">{navigation.map(([id, japanese, english]) => <button key={id} className={`rounded-lg px-3 py-2 text-left text-sm ${active === id ? "bg-amber-400/15 text-amber-200" : "text-stone-300 hover:bg-white/5"}`} onClick={() => select(id)}>{language === "ja" ? japanese : english}</button>)}</nav><div className="mt-6 border-t border-white/10 pt-5"><p className="mb-2 text-xs text-stone-400">{t("language")}</p><button type="button" role="switch" aria-checked={language === "en"} aria-label={t("language")} onClick={switchLanguage} className="flex w-full items-center justify-between rounded-lg bg-stone-800 px-3 py-2 text-sm"><span>{language === "ja" ? "日本語" : "English"}</span><span className="rounded bg-amber-400 px-2 py-0.5 text-xs font-bold text-stone-950">{language === "ja" ? "EN" : "日本語"}</span></button></div></aside><main className="flex flex-1 px-6 py-10 sm:px-10">{error && <p role="alert" className="fixed bottom-5 right-5 z-10 max-w-md rounded-lg border border-red-400/30 bg-stone-900 p-3 text-sm text-red-200">{error}</p>}{active === "roots" ? rootsView : active === "settings" ? settings : browser}</main>{detailBookId && <BookDetailsPanel bookId={detailBookId} onClose={() => setDetailBookId(null)} onSaved={() => void load()} />}</div></div>;
}
